In [4]:
import pandas as pd
import os
import multiprocessing
import functions_stanza

/home/christopher/projects/corpus_tryout/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-03-09 16:01:00 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 22.9MB/s]
2026-03-09 16:01:00 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-09 16:01:01 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-09 16:01:01 INFO: Using device: cpu
2026-03-09 16:01:01 INFO: Loading: tokenize
2026-03-09 16:01:02 INFO: Loading: mwt
2026-03-09 16:01:02 INFO: Loading: pos
2026-03-09 16:01:04 INFO: Loading: lemma
2026-03-09 16:01:04 INFO: Loading: constituency
2026-03-09 16:01:05 INFO: Loading: depparse
2026-03-09 16:01:05 INFO: Loading: sentiment
2026-03-09 16:01:05 INFO: Loading: ner
2026-03-09 16:01:07 INFO: Done loading processors!
2026-03-09 16:01:07 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 27.4MB/s]
2026-03-09 16:01:07 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-09 16:01:08 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-09 16:01:08 INFO: Using device: cpu
2026-03-09 16:01:08 INFO: Loading: tokenize
2026-03-09 16:01:08 INFO: Loading: pos
2026-03-09 16:01:09 INFO: Loading: lemma
2026-03-09 16:01:09 INFO: Loading: depparse
2026-03-09 16:01:10 INFO: Done loading processors!

In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
dfs = []

for file in os.listdir("gerunzius_download"):
    csv = pd.read_csv(f"gerunzius_download/{file}", sep=";", header=None)
    csv = csv.set_index(csv[0])
    csv = csv.drop(columns=[0])
    dfs.append(csv)

In [7]:
df = pd.concat(dfs)

In [8]:
df = df.sort_index()

In [9]:
df = df.drop_duplicates().reset_index(drop=True) # remove duplicates; export from kontext pretty iffy

In [10]:
df = df.fillna("")

In [11]:
df[3] = df[3].str.replace("-", "")

In [12]:
df["romanian"] = df[2] + " " + df[3] + " " + df[4]

In [13]:
replacements = [
    ("‘ ", "‘"),
    (" ’", "’"),
    (" ,", ","),
    (" .", "."),
    (" :", ":"),
    (" ?", "?"),
    ("( ", "("),
    (" )", ")"),
    (" ;", ";"),
    ("' ", "'"),
    (" '", "'"),
    (" -", "-"),
    ("- ", "-"),
]

In [14]:
for replacement in replacements:
    df["romanian"] = df["romanian"].str.replace(replacement[0], replacement[1])

In [15]:
for replacement in replacements:
    df[7] = df[7].str.replace(replacement[0], replacement[1])

In [16]:
CHUNK_SIZE = 2500

# Parse English

In [13]:
multiprocessing.set_start_method("spawn", force=True)

In [ ]:
process_en = multiprocessing.Process(
    target=functions_stanza.parse_in_chunks, args=(df, "en", 7, "gerunzius", CHUNK_SIZE)
)

In [15]:
process_en.start()

2026-03-03 12:06:19 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 29.1MB/s]
2026-03-03 12:06:20 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-03 12:06:21 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-03 12:06:21 INFO: Using device: cpu
2026-03-03 12:06:21 INFO: Loading: tokenize
2026-03-03 12:06:21 INFO: Loading: mwt
2026-03-03 12:06:21 INFO: Loading: pos
2026-03-03 12:06:23 INFO: Loading: lemma
2026-03-03 12:06:23 INFO: Loading: constituency
2026-03-03 12:06:24 INFO: Loading: depparse
2026-03-03 12:06:24 INFO: Loading: sentiment
2026-03-03 12:06:25 INFO: Loading: ner
2026-03-03 12:06:26 INFO: Done loading processors!
2026-03-03 12:06:26 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 26.8MB/s]
2026-03-03 12:06:27 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-03 12:06:28 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-03 12:06:28 INFO: Using device: cpu
2026-03-03 12:06:28 INFO: Loading: tokenize
2026-03-03 12:06:28 INFO: Loading: pos
2026-03-03 12:06:29 INFO: Loading: lemma
2026-03-03 12:06:30 INFO: Loading: depparse

Parsing chunk 0 to 2499

2026-03-03 12:06:30 INFO: Done loading processors!

In [17]:
parsed_dict_en = functions_stanza.load_pickled_data(folder="gerunzius", language="en")

parsed_slice_en_7500_9999.pkl
parsed_slice_en_10000_11261.pkl
parsed_slice_ro_0_2499.pkl
parsed_slice_en_2500_4999.pkl
parsed_slice_ro_5000_7499.pkl
parsed_slice_ro_10000_11261.pkl
parsed_slice_en_0_2499.pkl
parsed_slice_ro_7500_9999.pkl
parsed_slice_ro_2500_4999.pkl
parsed_slice_en_5000_7499.pkl

In [18]:
adv_part_indices_and_words = []

In [19]:
for i in range(0, len(parsed_dict_en)):
    adv_parts = functions_stanza.get_adv_part_in_sentences(parsed_dict_en[i])
    if adv_parts:
        adv_part_indices_and_words.append((i, adv_parts))

In [20]:
len(adv_part_indices_and_words)

5479

In [21]:
adv_part_indices_and_words

[(5, [('hurrying', 'hurry')]),
 (7, [('wondering', 'wonder')]),
 (8, [('wondering', 'wonder')]),
 (10, [('finding', 'find')]),
 (14, [('muttering', 'mutter')]),
 (15, [('muttering', 'mutter')]),
 (17, [('talking', 'talk')]),
 (22, [('trying', 'try')]),
 (23, [('trying', 'try')]),
 (29, [('licking', 'lick')]),
 (42, [('turning', 'turn')]),
 (43, [('rising', 'rise')]),
 (49, [('pointing', 'point')]),
 (50, [('calling', 'call')]),
 (51, [('turning', 'turn')]),
 (52, [('saying', 'say')]),
 (53, [('looking', 'look')]),
 (54, [('turning', 'turn')]),
 (55, [('turning', 'turn')]),
 (56, [('looking', 'look')]),
 (58, [('getting', 'get')]),
 (59, [('getting', 'get')]),
 (62, [('remarking', 'remark')]),
 (63, [('remarking', 'remark')]),
 (64, [('hoping', 'hope')]),
 (65, [('trotting', 'trot')]),
 (70, [('saying', 'say')]),
 (72, [('taking', 'take')]),
 (73, [('taking', 'take')]),
 (74, [('forgetting', 'forget')]),
 (78, [('scratching', 'scratch'), ('saying', 'say')]),
 (83, [('trying', 'try')]),
 (85, [('knowing', 'know')]),
 (89, [('thinking', 'think')]),
 (90, [('running', 'run')]),
 (91, [('running', 'run')]),
 (92, [('running', 'run')]),
 (93, [('running', 'run')]),
 (94, [('running', 'run')]),
 (97, [('swallowing', 'swallow')]),
 (98, [('rearing', 'rear')]),
 (100, [('remarking', 'remark')]),
 (101, [('trying', 'try')]),
 (110, [('raising', 'raise')]),
 (114, [('judging', 'judge')]),
 (115, [('judging', 'judge')]),
 (116, [('judging', 'judge')]),
 (117, [('saying', 'say')]),
 (118, [('changing', 'change')]),
 (120, [('staring', 'stare')]),
 (124, [('nursing', 'nurse'), ('stirring', 'stir')]),
 (130, [('flinging', 'fling')]),
 (139, [('waving', 'wave'), ('waving', 'wave')]),
 (140, [('waving', 'wave'), ('waving', 'wave')]),
 (142, [('expecting', 'expect')]),
 (143, [('beginning', 'begin')]),
 (144, [('beginning', 'begin')]),
 (145, [('beginning', 'begin')]),
 (147, [('resting', 'rest')]),
 (148, [('resting', 'rest')]),
 (151, [('turning', 'turn'), ('shaking', 'shake')]),
 (152, [('turning', 'turn'), ('shaking', 'shake')]),
 (153, [('turning', 'turn'), ('shaking', 'shake')]),
 (154, [('looking', 'look')]),
 (157, [('turning', 'turn')]),
 (158, [('tossing', 'toss')]),
 (159, [('yawning', 'yawn')]),
 (161, [('forgetting', 'forget')]),
 (164, [('yawning', 'yawn')]),
 (165, [('yawning', 'yawn')]),
 (168, [('hoping', 'hope')]),
 (174, [('carrying', 'carry')]),
 (175, [('tossing', 'toss')]),
 (176, [('pointing', 'point')]),
 (179, [('turning', 'turn')]),
 (180, [('going', 'go')]),
 (183, [('looking', 'look')]),
 (184, [('looking', 'look')]),
 (186, [('tumbling', 'tumble')]),
 (187, [('quarrelling', 'quarrell')]),
 (188, [('quarrelling', 'quarrell')]),
 (189, [('quarrelling', 'quarrell')]),
 (190, [('quarrelling', 'quarrell')]),
 (191, [('quarrelling', 'quarrell')]),
 (195, [('coming', 'come')]),
 (196, [('coming', 'come')]),
 (198, [('screaming', 'scream')]),
 (204, [('digging', 'digg')]),
 (206, [('frowning', 'frown')]),
 (207, [('stamping', 'stamp')]),
 (208, [('remarking', 'remark')]),
 (209, [('remarking', 'remark')]),
 (215, [('leaving', 'leave')]),
 (217, [('sitting', 'sit')]),
 (221, [('counting', 'count')]),
 (223, [('sighing', 'sigh')]),
 (230, [('capering', 'caper')]),
 (231, [('dropping', 'drop')]),
 (238, [('wondering', 'wonder')]),
 (240, [('taking', 'take')]),
 (246, [('turning', 'turn')]),
 (247, [('looking', 'look')]),
 (248, [('looking', 'look')]),
 (253, [('feeling', 'feel')]),
 (254,
  [('forgetting', 'forget'),
   ('upsetting', 'upsetting'),
   ('reminding', 'remind')]),
 (255, [('turning', 'turn')]),
 (258, [('rubbing', 'rub')]),
 (259, [('spreading', 'spread'), ('turning', 'turn')]),
 (260, [('spreading', 'spread'), ('turning', 'turn')]),
 (261, [('spreading', 'spread'), ('turning', 'turn')]),
 (262, [('pointing', 'point')]),
 (263, [('throwing', 'throw')]),
 (264, [('using', 'use')]),
 (265, [('looking', 'look')]),
 (266, [('turning', 'turn')]),
 (268, [('thinking', 'think')]),
 (269, [('leaning', 'lean'), ('watching', 'watch')]),
 (275, [('remembering', 'remember')]),
 (276, [('remembering', 'remember')]),
 (277, [('remembering', 'remember')]),
 (278, [('remembering', 'remember')]),
 (280, [('making', 'make')]),
 (282, [('studying', 'study')]),
 (283, [('indicating', 'indicate')]),
 (284, [('firing', 'fire')]),
 (285, [('taking', 'take')]),
 (287, [('thinking', 'think'), ('knowing', 'know')]),
 (288, [('thinking', 'think'), ('knowing', 'know')]),
 (289, [('feeling', 'feel')]),
 (290, [('feeling', 'feel')]),
 (291, [('covering', 'cover')]),
 (293, [('carrying', 'carry')]),
 (295, [('looking', 'look')]),
 (296, [('walking', 'walk')]),
 (298, [('separating', 'separate')]),
 (299, [('popping', 'popp')]),
 (300, [('leaving', 'leave')]),
 (303, [('clutching', 'clutch')]),
 (304, [('thinking', 'think')]),
 (308, [('wiping', 'wipe')]),
 (309, [('extending', 'extend')]),
 (313, [('turning', 'turn')]),
 (314, [('hoping', 'hope')]),
 (315, [('ironing', 'irone'), ('stopping', 'stop')]),
 (318, [('climbing', 'climb'), ('holding', 'hold')]),
 (319, [('climbing', 'climb'), ('holding', 'hold')]),
 (320, [('climbing', 'climb'), ('holding', 'hold')]),
 (321, [('edging', 'edg')]),
 (323, [('Peeking', 'peek')]),
 (324, [('touching', 'touch')]),
 (326, [('trying', 'try')]),
 (327, [('falling', 'fall'), ('holding', 'hold')]),
 (332, [('keeping', 'keep')]),
 (335, [('waiting', 'wait')]),
 (336, [('picking', 'pick')]),
 (337, [('thinking', 'think')]),
 (338, [('dividing', 'divide')]),
 (339, [('jumping', 'jump')]),
 (340, [('jumping', 'jump')]),
 (341, [('grabbing', 'grab')]),
 (342, [('holding', 'hold')]),
 (343, [('feeling', 'feel')]),
 (345, [('gazing', 'gaze')]),
 (347, [('brightening', 'brighten')]),
 (353, [('holding', 'hold')]),
 (354, [('chuckling', 'chuckle')]),
 (355, [('glancing', 'glance')]),
 (356, [('dusting', 'dust')]),
 (357, [('moving', 'move')]),
 (361, [('trying', 'try')]),
 (362, [('closing', 'close')]),
 (366, [('closing', 'close')]),
 (368, [('waiting', 'wait')]),
 (369, [('maintaining', 'maintain')]),
 (371, [('feeling', 'feel')]),
 (372, [('smiling', 'smile')]),
 (373, [('smiling', 'smile')]),
 (375, [('telling', 'tell')]),
 (377, [('rubbing', 'rub')]),
 (378, [('cradling', 'cradl')]),
 (380, [('trying', 'try')]),
 (383, [('working', 'work'), ('listening', 'listen')]),
 (384, [('working', 'work'), ('listening', 'listen')]),
 (385, [('working', 'work'), ('listening', 'listen')]),
 (386, [('leaning', 'lean')]),
 (390, [('hanging', 'hang'), ('shifting', 'shift'), ('trying', 'try')]),
 (391, [('hanging', 'hang'), ('shifting', 'shift'), ('trying', 'try')]),
 (392, [('hanging', 'hang'), ('shifting', 'shift'), ('trying', 'try')]),
 (393, [('leaving', 'leave')]),
 (395, [('pushing', 'push')]),
 (402, [('holding', 'hold')]),
 (404, [('thanking', 'thank')]),
 (406, [('nodding', 'nodd')]),
 (407, [('talking', 'talk')]),
 (408, [('leaning', 'lean')]),
 (409, [('holding', 'hold')]),
 (411, [('hunching', 'hunch')]),
 (412, [('frowning', 'frown')]),
 (413, [('turning', 'turn')]),
 (415, [('smiling', 'smile')]),
 (416, [('thinking', 'think')]),
 (417, [('leaving', 'leave')]),
 (418, [('shifting', 'shift')]),
 (419, [('using', 'use')]),
 (424, [('leaving', 'leave')]),
 (432, [('swearing', 'swear')]),
 (434, [('knowing', 'know')]),
 (435, [('turning', 'turn')]),
 (436, [('ignoring', 'ignore')]),
 (439, [('describing', 'describe')]),
 (441, [('removing', 'remove')]),
 (442, [('removing', 'remove')]),
 (444, [('climbing', 'climb'), ('looking', 'look')]),
 (445, [('chuckling', 'chuckle')]),
 (448, [('playing', 'play')]),
 (450, [('leaning', 'lean')]),
 (451, [('lingering', 'linger')]),
 (452, [('hoping', 'hope')]),
 (453, [('smiling', 'smile')]),
 (454, [('wiping', 'wipe')]),
 (455, [('thinking', 'think')]),
 (458, [('watching', 'watch')]),
 (460, [('trying', 'try')]),
 (461, [('treating', 'treat')]),
 (464, [('placing', 'place')]),
 (465, [('placing', 'place')]),
 (468, [('weighing', 'weigh')]),
 (469, [('pouring', 'pour')]),
 (470, [('tapping', 'tap')]),
 (472, [('checking', 'check')]),
 (479, [('forcing', 'force')]),
 (480, [('feeling', 'feel')]),
 (482, [('blotting', 'blot')]),
 (484, [('folding', 'fold')]),
 (485, [('folding', 'fold')]),
 (489, [('checking', 'check')]),
 (494, [('leaning', 'lean'), ('grabbing', 'grab'), ('sinking', 'sink')]),
 (495, [('leaning', 'lean'), ('grabbing', 'grab'), ('sinking', 'sink')]),
 (496, [('leaning', 'lean'), ('grabbing', 'grab'), ('sinking', 'sink')]),
 (501, [('returning', 'return')]),
 (502, [('making', 'make')]),
 (507, [('jerking', 'jerk')]),
 (508, [('gripping', 'grip')]),
 (509, [('feeling', 'feel')]),
 (510, [('mixing', 'mix')]),
 (512, [('carrying', 'carry')]),
 (514, [('greeting', 'greeting')]),
 (516, [('promising', 'promise')]),
 (519, [('hoping', 'hope')]),
 (520, [('smiling', 'smile')]),
 (523, [('leaning', 'lean')]),
 (529, [('leaving', 'leave')]),
 (530, [('pressing', 'press')]),
 (531, [('capturing', 'capture')]),
 (534, [('picking', 'pick')]),
 (535, [('picking', 'pick')]),
 (536, [('leaving', 'leave')]),
 (541, [('jerking', 'jerk')]),
 (542, [('frowning', 'frown')]),
 (543, [('waiting', 'wait')]),
 (544, [('picking', 'pick')]),
 (547, [('nodding', 'nodd')]),
 (550, [('shaking', 'shake')]),
 (551, [('sitting', 'sit'), ('watching', 'watch')]),
 (552, [('sitting', 'sit'), ('watching', 'watch')]),
 (553, [('sitting', 'sit'), ('watching', 'watch')]),
 (554, [('waiting', 'wait')]),
 (555, [('clutching', 'clutch'), ('making', 'make')]),
 (556, [('clutching', 'clutch'), ('making', 'make')]),
 (567, [('seeking', 'seek')]),
 (568, [('jumping', 'jump')]),
 (569, [('jumping', 'jump')]),
 (572, [('Turning', 'turn')]),
 (573, [('Turning', 'turn')]),
 (574, [('twisting', 'twist'), ('making', 'make')]),
 (575, [('twisting', 'twist'), ('making', 'make')]),
 (576, [('twisting', 'twist'), ('making', 'make')]),
 (577, [('twisting', 'twist'), ('making', 'make')]),
 (578, [('twisting', 'twist'), ('making', 'make')]),
 (581, [('looking', 'look')]),
 (587, [('glancing', 'glance')]),
 (591, [('wondering', 'wonder')]),
 (593, [('wedging', 'wedg')]),
 (594, [('frowning', 'frown')]),
 (595, [('sitting', 'sit')]),
 (600, [('making', 'make')]),
 (604, [('deserting', 'desert')]),
 (611, [('trying', 'try')]),
 (612, [('trying', 'try')]),
 (613, [('trying', 'try')]),
 (614, [('ceasing', 'cease')]),
 (617, [('tossing', 'toss')]),
 (618, [('finding', 'find')]),
 (621, [('surprising', 'surprising')]),
 (623, [('leaving', 'leave')]),
 (624, [('turning', 'turn')]),
 (627, [('leaving', 'leave'), ('chatting', 'chat')]),
 (628, [('taking', 'take')]),
 (631, [('wiping', 'wipe')]),
 (633, [('walking', 'walk'), ('looking', 'look')]),
 (634, [('walking', 'walk'), ('looking', 'look')]),
 (635, [('mingling', 'mingle')]),
 (636, [('mingling', 'mingle')]),
 (639, [('exchanging', 'exchang')]),
 (641, [('leaning', 'lean')]),
 (642, [('wriggling', 'wriggle')]),
 (643, [('wriggling', 'wriggle')]),
 (645, [('cutting', 'cut')]),
 (646, [('Throwing', 'throw')]),
 (653, [('breaking', 'break')]),
 (656, [('looking', 'look')]),
 (657, [('looking', 'look')]),
 (659, [('staring', 'stare')]),
 (660, [('staring', 'stare')]),
 (661, [('drawing', 'draw')]),
 (662, [('drawing', 'draw')]),
 (663, [('drawing', 'draw')]),
 (665, [('looking', 'look')]),
 (666, [('looking', 'look')]),
 (667, [('leaning', 'lean')]),
 (668, [('leaning', 'lean')]),
 (669, [('advancing', 'advance')]),
 (677, [('staring', 'stare')]),
 (678, [('Taking', 'take')]),
 (679, [('muttering', 'mutter')]),
 (683, [('trembling', 'tremble')]),
 (688, [('changing', 'change')]),
 (689, [('standing', 'stand')]),
 (690, [('knowing', 'know')]),
 (691, [('raising', 'raise')]),
 (692, [('Eluding', 'elude')]),
 (698, [('washing', 'wash')]),
 (699, [('pawing', 'paw')]),
 (700, [('pawing', 'paw')]),
 (702, [('taking', 'take')]),
 (703, [('taking', 'take')]),
 (704, [('making', 'make')]),
 (705, [('endowing', 'endow')]),
 (706, [('Reading', 'read')]),
 (708, [('wasting', 'waste')]),
 (709, [('wasting', 'waste')]),
 (710, [('wasting', 'waste')]),
 (711, [('wasting', 'waste')]),
 (717, [('Imagining', 'imagin')]),
 (719, [('moving', 'move')]),
 (728, [('Sitting', 'sit')]),
 (733, [('looking', 'look')]),
 (736, [('pocketing', 'pocket')]),
 (739, [('tipping', 'tip')]),
 (742, [('talking', 'talk')]),
 (745, [('remembering', 'remember')]),
 (748, [('leaning', 'lean')]),
 (749, [('leaving', 'leave')]),
 (754, [('rubbing', 'rub')]),
 (755, [('rubbing', 'rub')]),
 (756, [('rubbing', 'rub')]),
 (759, [('tightening', 'tighten')]),
 (760, [('Turning', 'turn')]),
 (764, [('looking', 'look')]),
 (765, [('hoping', 'hope')]),
 (767, [('dragging', 'drag')]),
 (768, [('judging', 'judge')]),
 (775, [('shaking', 'shake')]),
 (776, [('opening', 'open')]),
 (778, [('leaning', 'lean')]),
 (779, [('leaning', 'lean')]),
 (780, [('rising', 'rise')]),
 (782, [('looking', 'look')]),
 (793, [('Recovering', 'recover')]),
 (795, [('examining', 'examine')]),
 (797, [('examining', 'examine')]),
 (799, [('calling', 'call')]),
 (800, [('cutting', 'cut')]),
 (803, [('adding', 'add'), ('decking', 'decking')]),
 (804, [('adding', 'add'), ('decking', 'decking')]),
 (805, [('leaving', 'leave')]),
 (811, [('suspecting', 'suspect')]),
 (812, [('resting', 'rest')]),
 (819, [('ringing', 'ring')]),
 (820, [('ringing', 'ring')]),
 (821, [('realizing', 'realize')]),
 (822, [('disappearing', 'disappear')]),
 (825, [('adding', 'add')]),
 (834, [('bringing', 'bring')]),
 (835, [('bringing', 'bring')]),
 (836, [('following', 'follow')]),
 (839, [('nodding', 'nodd')]),
 (841, [('listening', 'listen')]),
 (842, [('Wondering', 'wonder')]),
 (845, [('holding', 'hold')]),
 (846, [('carrying', 'carry')]),
 (847, [('indicating', 'indicate')]),
 (850, [('kissing', 'kiss')]),
 (853, [('holding', 'hold')]),
 (856, [('turning', 'turn')]),
 (858, [('preceding', 'preced')]),
 (860, [('beating', 'beat'), ('moulding', 'mould')]),
 (861, [('beating', 'beat'), ('moulding', 'mould')]),
 (862, [('beating', 'beat'), ('moulding', 'mould')]),
 (864, [('shuffling', 'shuffle')]),
 (865, [('wrapping', 'wrap')]),
 (868, [('pressing', 'press')]),
 (869, [('touching', 'touch')]),
 (870, [('leaving', 'leave')]),
 (871, [('leaving', 'leave')]),
 (872, [('realizing', 'realize')]),
 (874, [('breathing', 'breathe')]),
 (876, [('shading', 'shade')]),
 (877, [('shading', 'shade')]),
 (883, [('fixing', 'fix')]),
 (888, [('smiling', 'smile')]),
 (894, [('denying', 'deny'), ('defending', 'defend')]),
 (895, [('denying', 'deny'), ('defending', 'defend')]),
 (896, [('trying', 'try'), ('struggling', 'struggle')]),
 (897, [('trying', 'try'), ('struggling', 'struggle')]),
 (898, [('trying', 'try'), ('struggling', 'struggle')]),
 (900, [('exulting', 'exult')]),
 (902, [('saying', 'say')]),
 (903, [('intending', 'intend')]),
 (904, [('waving', 'wave')]),
 (905, [('waving', 'wave')]),
 (912, [('swaying', 'sway')]),
 (913, [('swaying', 'sway')]),
 (919, [('passing', 'pass')]),
 (920, [('passing', 'pass')]),
 (921, [('passing', 'pass')]),
 (922, [('passing', 'pass')]),
 (929, [('intending', 'intend')]),
 (932, [('Crossing', 'cross')]),
 (937, [('watching', 'watch')]),
 (938, [('watching', 'watch')]),
 (941, [('Crossing', 'cross')]),
 (944, [('Throwing', 'throw')]),
 (947, [('pervading', 'pervade')]),
 (949, [('leaving', 'leave')]),
 (950, [('leaving', 'leave')]),
 (955, [('summing', 'summ')]),
 (956, [('filling', 'fill')]),
 (957, [('filling', 'fill')]),
 (964, [('concealing', 'conceal')]),
 (967, [('Taking', 'take')]),
 (973, [('trying', 'try')]),
 (974, [('pointing', 'point')]),
 (975, [('holding', 'hold')]),
 (979, [('nodding', 'nodd')]),
 (980, [('nodding', 'nodd')]),
 (982, [('going', 'go'), ('inquiring', 'inquire')]),
 (983, [('going', 'go'), ('inquiring', 'inquire')]),
 (989, [('tracing', 'trace')]),
 (1000, [('trying', 'try')]),
 (1003, [('holding', 'hold')]),
 (1004, [('remarking', 'remark')]),
 (1019, [('moving', 'move'), ('adapting', 'adapt')]),
 (1020, [('moving', 'move'), ('adapting', 'adapt')]),
 (1021, [('holding', 'hold')]),
 (1028, [('throwing', 'throw')]),
 (1029, [('throwing', 'throw')]),
 (1032, [('smoking', 'smoke')]),
 (1033, [('smoking', 'smoke')]),
 (1034, [('smoking', 'smoke')]),
 (1035, [('shuffling', 'shuffle')]),
 (1036, [('shuffling', 'shuffle')]),
 (1037, [('reading', 'read')]),
 (1044, [('carrying', 'carry')]),
 (1045, [('carrying', 'carry')]),
 (1046, [('carrying', 'carry')]),
 (1047, [('carrying', 'carry')]),
 (1048, [('carrying', 'carry')]),
 (1053, [('digging', 'digg')]),
 (1057, [('sniffing', 'sniff')]),
 (1058, [('saying', 'say')]),
 (1067, [('wearing', 'wear')]),
 (1069, [('watching', 'watch')]),
 (1070, [('saying', 'say')]),
 (1071, [('saying', 'say')]),
 (1076, [('waiting', 'wait'), ('dawdling', 'dawdle')]),
 (1079, [('calling', 'call')]),
 (1082, [('looking', 'look')]),
 (1103, [('watering', 'water')]),
 (1106, [('ruing', 'ruing')]),
 (1108, [('glorying', 'glory')]),
 (1113, [('threading', 'thread'), ('staring', 'stare')]),
 (1118, [('looking', 'look')]),
 (1123, [('talking', 'talk'), ('asking', 'ask')]),
 (1124, [('talking', 'talk'), ('asking', 'ask')]),
 (1131, [('getting', 'get')]),
 (1135, [('punching', 'punch')]),
 (1137, [('reverting', 'revert')]),
 (1139, [('figuring', 'figure')]),
 (1145, [('bringing', 'bring')]),
 (1146, [('turning', 'turn')]),
 (1149, [('turning', 'turn')]),
 (1150, [('turning', 'turn')]),
 (1151, [('turning', 'turn')]),
 (1152, [('clutching', 'clutch')]),
 (1153, [('imitating', 'imitate')]),
 (1154, [('bowing', 'bow')]),
 (1155, [('bowing', 'bow')]),
 (1156, [('rising', 'rise')]),
 (1157, [('rising', 'rise')]),
 (1158, [('rising', 'rise')]),
 (1164, [('looking', 'look')]),
 (1167, [('spending', 'spend')]),
 (1168, [('arriving', 'arrive')]),
 (1170, [('waiting', 'wait')]),
 (1173, [('raising', 'raise')]),
 (1174, [('raising', 'raise')]),
 (1175, [('raising', 'raise')]),
 (1176, [('raising', 'raise')]),
 (1180, [('knowing', 'know')]),
 (1181, [('shifting', 'shift')]),
 (1182, [('shifting', 'shift')]),
 (1183, [('reading', 'read')]),
 (1186, [('trying', 'try')]),
 (1187, [('looking', 'look')]),
 (1190, [('devising', 'devise')]),
 (1196, [('taking', 'take')]),
 (1198, [('carrying', 'carry')]),
 (1203, [('switching', 'switch')]),
 (1211, [('closing', 'close')]),
 (1213, [('suspicioning', 'suspicion'), ('thinking', 'think')]),
 (1221, [('looking', 'look')]),
 (1222, [('wetting', 'wet')]),
 (1224, [('fingering', 'finger')]),
 (1225, [('fingering', 'finger')]),
 (1229, [('thumbing', 'thumb')]),
 (1230, [('thumbing', 'thumb')]),
 (1233, [('asking', 'ask')]),
 (1246, [('digging', 'digg')]),
 (1254, [('Sighing', 'sigh')]),
 (1257, [('cursing', 'curse')]),
 (1258, [('talking', 'talk')]),
 (1259, [('talking', 'talk')]),
 (1260, [('putting', 'put')]),
 (1262, [('slamming', 'slamm')]),
 (1263, [('carrying', 'carry')]),
 (1264, [('eating', 'eat')]),
 (1265, [('hoping', 'hope')]),
 (1269, [('commanding', 'commanding')]),
 (1270, [('commanding', 'commanding')]),
 (1271, [('hitting', 'hit')]),
 (1272, [('hitting', 'hit')]),
 (1276, [('seeing', 'see')]),
 (1277, [('trying', 'try')]),
 (1281, [('crossing', 'cross')]),
 (1285, [('telling', 'tell')]),
 (1290, [('listening', 'listen')]),
 (1291, [('listening', 'listen')]),
 (1292, [('rolling', 'roll')]),
 (1293, [('rolling', 'roll')]),
 (1294, [('rubbing', 'rub')]),
 (1295, [('rubbing', 'rub')]),
 (1297, [('poking', 'poke')]),
 (1298, [('looking', 'look')]),
 (1299, [('looking', 'look')]),
 (1300, [('looking', 'look')]),
 (1301, [('fluttering', 'flutter')]),
 (1303, [('promising', 'promise')]),
 (1304, [('kissing', 'kiss')]),
 (1310, [('waking', 'wake')]),
 (1311, [('waking', 'wake')]),
 (1312, [('watching', 'watch')]),
 (1313, [('watching', 'watch')]),
 (1315, [('Taking', 'take')]),
 (1316, [('clasping', 'clasp')]),
 (1318, [('asserting', 'assert'), ('stealing', 'steal')]),
 (1319, [('going', 'go')]),
 (1321, [('trying', 'try')]),
 (1324, [('nodding', 'nodd')]),
 (1326, [('swerving', 'swerve')]),
 (1327, [('trying', 'try')]),
 (1331, [('digging', 'digg')]),

# Parse Romanian

In [14]:
multiprocessing.set_start_method("spawn", force=True)

In [15]:
process_ro = multiprocessing.Process(
    target=functions_stanza.parse_in_chunks,
    args=(df, "ro", "romanian", "gerunzius", CHUNK_SIZE),
)

In [ ]:
process_ro.start()

2026-03-09 14:50:46 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 25.7MB/s]
2026-03-09 14:50:46 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-09 14:50:47 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2026-03-09 14:50:47 INFO: Using device: cpu
2026-03-09 14:50:47 INFO: Loading: tokenize
2026-03-09 14:50:48 INFO: Loading: mwt
2026-03-09 14:50:48 INFO: Loading: pos
2026-03-09 14:50:49 INFO: Loading: lemma
2026-03-09 14:50:50 INFO: Loading: constituency
2026-03-09 14:50:50 INFO: Loading: depparse
2026-03-09 14:50:50 INFO: Loading: sentiment
2026-03-09 14:50:51 INFO: Loading: ner
2026-03-09 14:50:53 INFO: Done loading processors!
2026-03-09 14:50:53 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 25.7MB/s]
2026-03-09 14:50:53 INFO: Downloaded file to /home/christopher/stanza_resources/resources.json
2026-03-09 14:50:53 INFO: Loading these models for language: ro (Romanian):
============================
| Processor | Package      |
----------------------------
| tokenize  | rrt          |
| pos       | rrt_nocharlm |
| lemma     | rrt_nocharlm |
| depparse  | rrt_nocharlm |
============================

2026-03-09 14:50:53 INFO: Using device: cpu
2026-03-09 14:50:53 INFO: Loading: tokenize
2026-03-09 14:50:53 INFO: Loading: pos
2026-03-09 14:50:55 INFO: Loading: lemma
2026-03-09 14:50:55 INFO: Loading: depparse
2026-03-09 14:50:55 INFO: Done loading processors!

Parsing chunk 0 to 2499

Parsing chunk 2500 to 4999
Parsing chunk 5000 to 7499
Parsing chunk 7500 to 9999
Parsing chunk 10000 to 11261

In [22]:
parsed_dict_ro = functions_stanza.load_pickled_data(folder="gerunzius", language="ro")

parsed_slice_en_7500_9999.pkl
parsed_slice_en_10000_11261.pkl
parsed_slice_ro_0_2499.pkl
parsed_slice_en_2500_4999.pkl
parsed_slice_ro_5000_7499.pkl
parsed_slice_ro_10000_11261.pkl
parsed_slice_en_0_2499.pkl
parsed_slice_ro_7500_9999.pkl
parsed_slice_ro_2500_4999.pkl
parsed_slice_en_5000_7499.pkl

In [23]:
gerunziu_indices_and_lemmas = []

In [24]:
for i in range(0, len(df)):
    row = df.iloc[i]
    contains_gerunziu, lemma_of_gerunziu = functions_stanza.sentences_contain_gerunziu(
        row[3], parsed_dict_ro[i]
    )
    if contains_gerunziu:
        gerunziu_indices_and_lemmas.append((i, lemma_of_gerunziu))

{
  "id": 14,
  "text": "bombănind",
  "lemma": "bombăni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 11,
  "deprel": "advcl",
  "start_char": 66,
  "end_char": 75
}
{
  "id": 1,
  "text": "Văzând",
  "lemma": "vedea",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 8,
  "deprel": "advcl",
  "start_char": 102,
  "end_char": 108
}
{
  "id": 3,
  "text": "alunecând",
  "lemma": "aluneca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 184,
  "end_char": 193
}
{
  "id": 6,
  "text": "plimbându",
  "lemma": "plimba",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 291,
  "end_char": 300
}
{
  "id": 13,
  "text": "întrebând",
  "lemma": "întreba",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 6,
  "deprel": "conj",
  "start_char": 429,
  "end_char": 438
}
{
  "id": 18,
  "text": "alergând",
  "lemma": "alerga",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 13,
  "deprel": "advcl",
  "start_char": 565,
  "end_char": 573
}
{
  "id": 17,
  "text": "bombănind",
  "lemma": "bombăni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 16,
  "deprel": "advcl",
  "start_char": 700,
  "end_char": 709
}
{
  "id": 13,
  "text": "încercând",
  "lemma": "încerca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 22,
  "deprel": "advcl",
  "start_char": 805,
  "end_char": 814
}
{
  "id": 27,
  "text": "întrebându",
  "lemma": "întrebându",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 22,
  "deprel": "advcl",
  "start_char": 1063,
  "end_char": 1073
}
{
  "id": 10,
  "text": "trăgând",
  "lemma": "trage",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 1171,
  "end_char": 1178
}
{
  "id": 3,
  "text": "găsind",
  "lemma": "găsi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 43,
  "deprel": "advcl",
  "start_char": 1342,
  "end_char": 1348
}
{
  "id": 17,
  "text": "făcând",
  "lemma": "face",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 25,
  "deprel": "advcl",
  "start_char": 1648,
  "end_char": 1654
}
{
  "id": 7,
  "text": "întrebându",
  "lemma": "întrebându",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 1812,
  "end_char": 1822
}
{
  "id": 8,
  "text": "ţinându",
  "lemma": "ţina",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 1888,
  "end_char": 1895
}
{
  "id": 6,
  "text": "ţinând",
  "lemma": "ţinca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 2028,
  "end_char": 2034
}
{
  "id": 5,
  "text": "bombănind",
  "lemma": "bombăni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 2172,
  "end_char": 2181
}
{
  "id": 19,
  "text": "apropiindu",
  "lemma": "apropii",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 18,
  "deprel": "advcl",
  "start_char": 2306,
  "end_char": 2316
}
{
  "id": 27,
  "text": "spunându",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 22,
  "deprel": "advcl",
  "start_char": 2488,
  "end_char": 2496
}
{
  "id": 17,
  "text": "încercând",
  "lemma": "încerca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 2604,
  "end_char": 2613
}
{
  "id": 11,
  "text": "izbucnind",
  "lemma": "izbucni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 8,
  "deprel": "advcl",
  "start_char": 2724,
  "end_char": 2733
}
{
  "id": 26,
  "text": "băgându",
  "lemma": "băga",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 23,
  "deprel": "advcl",
  "start_char": 2936,
  "end_char": 2943
}
{
  "id": 2,
  "text": "spunând",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 6,
  "deprel": "advcl",
  "start_char": 2993,
  "end_char": 3000
}
{
  "id": 19,
  "text": "înotând",
  "lemma": "înota",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 16,
  "deprel": "advcl",
  "start_char": 3282,
  "end_char": 3289
}
{
  "id": 21,
  "text": "sirăduindu",
  "lemma": "sirădui",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 19,
  "deprel": "conj",
  "start_char": 3425,
  "end_char": 3435
}
{
  "id": 8,
  "text": "plescăind",
  "lemma": "plescăi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 6,
  "deprel": "advcl",
  "start_char": 3512,
  "end_char": 3521
}
{
  "id": 14,
  "text": "amintindu",
  "lemma": "aminti",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 22,
  "deprel": "advcl",
  "start_char": 3625,
  "end_char": 3634
}
{
  "id": 18,
  "text": "clipind",
  "lemma": "clipi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 15,
  "deprel": "advcl",
  "start_char": 3828,
  "end_char": 3835
}
{
  "id": 9,
  "text": "tremurând",
  "lemma": "tremura",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 3943,
  "end_char": 3952
}
{
  "id": 13,
  "text": "temându",
  "lemma": "temandu",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 8,
  "deprel": "advcl",
  "start_char": 4048,
  "end_char": 4055
}
{
  "id": 13,
  "text": "continuând",
  "lemma": "continua",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 4173,
  "end_char": 4183
}
{
  "id": 7,
  "text": "grăbindu",
  "lemma": "grăbi",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 4264,
  "end_char": 4272
}
{
  "id": 15,
  "text": "stârnind",
  "lemma": "stârni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 11,
  "deprel": "advcl",
  "start_char": 4425,
  "end_char": 4433
}
{
  "id": 21,
  "text": "tremurând",
  "lemma": "tremura",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 15,
  "deprel": "advcl",
  "start_char": 4582,
  "end_char": 4591
}
{
  "id": 29,
  "text": "şiroind",
  "lemma": "şiroi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 10,
  "deprel": "advcl",
  "start_char": 4759,
  "end_char": 4766
}
{
  "id": 37,
  "text": "simţindu",
  "lemma": "simţi",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 29,
  "deprel": "conj",
  "start_char": 5050,
  "end_char": 5058
}
{
  "id": 3,
  "text": "vorbind",
  "lemma": "vorbi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 5124,
  "end_char": 5131
}
{
  "id": 19,
  "text": "spunând",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 17,
  "deprel": "advcl",
  "start_char": 5329,
  "end_char": 5336
}
{
  "id": 5,
  "text": "formând",
  "lemma": "forma",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 3,
  "deprel": "advcl",
  "start_char": 5399,
  "end_char": 5406
}
{
  "id": 7,
  "text": "luându",
  "lemma": "lua",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 5506,
  "end_char": 5512
}
{
  "id": 7,
  "text": "tremurând",
  "lemma": "tremura",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 5578,
  "end_char": 5587
}
{
  "id": 12,
  "text": "cruntându",
  "lemma": "crunta",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 6,
  "deprel": "advcl",
  "start_char": 5666,
  "end_char": 5675
}
{
  "id": 10,
  "text": "vorbind",
  "lemma": "vorbi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 7,
  "deprel": "advcl",
  "start_char": 5747,
  "end_char": 5754
}
{
  "id": 4,
  "text": "întorcându",
  "lemma": "întoarce",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 5835,
  "end_char": 5845
}
{
  "id": 8,
  "text": "ridicându",
  "lemma": "ridica",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 6,
  "deprel": "advcl",
  "start_char": 5907,
  "end_char": 5916
}
{
  "id": 9,
  "text": "gâfâind",
  "lemma": "gâfâi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 6543,
  "end_char": 6550
}
{
  "id": 14,
  "text": "întrebând",
  "lemma": "întreba",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 9,
  "deprel": "conj",
  "start_char": 6670,
  "end_char": 6679
}
{
  "id": 8,
  "text": "ţinându",
  "lemma": "ţina",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 6738,
  "end_char": 6745
}
{
  "id": 9,
  "text": "arătând",
  "lemma": "arăta",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 6939,
  "end_char": 6946
}
{
  "id": 8,
  "text": "strigând",
  "lemma": "striga",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 3,
  "deprel": "advcl",
  "start_char": 7027,
  "end_char": 7035
}
{
  "id": 4,
  "text": "întorcându",
  "lemma": "întoarce",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 7109,
  "end_char": 7119
}
{
  "id": 17,
  "text": "spunând",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 13,
  "deprel": "advcl",
  "start_char": 76,
  "end_char": 83
}
{
  "id": 17,
  "text": "luându",
  "lemma": "lua",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 13,
  "deprel": "advcl",
  "start_char": 7332,
  "end_char": 7338
}
{
  "id": 9,
  "text": "întorcându",
  "lemma": "întoarce",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 7450,
  "end_char": 7460
}
{
  "id": 14,
  "text": "oftând",
  "lemma": "ofta",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 9,
  "deprel": "conj",
  "start_char": 7575,
  "end_char": 7581
}
{
  "id": 9,
  "text": "măsurând",
  "lemma": "măsura",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 7648,
  "end_char": 7656
}
{
  "id": 8,
  "text": "uitându",
  "lemma": "uita",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 3,
  "deprel": "advcl",
  "start_char": 7772,
  "end_char": 7779
}
{
  "id": 13,
  "text": "ridicându",
  "lemma": "ridica",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 9,
  "deprel": "advcl",
  "start_char": 7899,
  "end_char": 7908
}
{
  "id": 16,
  "text": "îndepărtându",
  "lemma": "îndepărta",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 13,
  "deprel": "conj",
  "start_char": 8037,
  "end_char": 8049
}
{
  "id": 4,
  "text": "îndrugând",
  "lemma": "îndruge",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 2,
  "deprel": "advcl",
  "start_char": 8100,
  "end_char": 8109
}
{
  "id": 16,
  "text": "suspinând",
  "lemma": "suspine",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 15,
  "deprel": "advcl",
  "start_char": 8212,
  "end_char": 8221
}
{
  "id": 9,
  "text": "zicând",
  "lemma": "zice",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 8327,
  "end_char": 8333
}
{
  "id": 7,
  "text": "zicându",
  "lemma": "zice",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 8388,
  "end_char": 8395
}
{
  "id": 13,
  "text": "crezând",
  "lemma": "crede",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 8479,
  "end_char": 8486
}
{
  "id": 4,
  "text": "aruncând",
  "lemma": "arunca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 8628,
  "end_char": 8636
}
{
  "id": 4,
  "text": "bombănind",
  "lemma": "bombăni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 3,
  "deprel": "advcl",
  "start_char": 8742,
  "end_char": 8751
}
{
  "id": 14,
  "text": "alergând",
  "lemma": "alerga",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 11,
  "deprel": "advcl",
  "start_char": 8823,
  "end_char": 8831
}
{
  "id": 11,
  "text": "temându",
  "lemma": "temandu",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 8901,
  "end_char": 8908
}
{
  "id": 20,
  "text": "punând",
  "lemma": "pune",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 16,
  "deprel": "advcl",
  "start_char": 9124,
  "end_char": 9130
}
{
  "id": 6,
  "text": "spunându",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 9249,
  "end_char": 9257
}
{
  "id": 26,
  "text": "spunându",
  "lemma": "spune",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 12,
  "deprel": "advcl",
  "start_char": 9398,
  "end_char": 9406
}
{
  "id": 4,
  "text": "gândind",
  "lemma": "gândi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 33,
  "deprel": "advcl",
  "start_char": 9443,
  "end_char": 9450
}
{
  "id": 18,
  "text": "purtând",
  "lemma": "purta",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 33,
  "deprel": "advcl",
  "start_char": 9739,
  "end_char": 9746
}
{
  "id": 29,
  "text": "uitând",
  "lemma": "uita",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 25,
  "deprel": "advcl",
  "start_char": 10016,
  "end_char": 10022
}
{
  "id": 9,
  "text": "încercând",
  "lemma": "încerca",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 5,
  "deprel": "advcl",
  "start_char": 10218,
  "end_char": 10227
}
{
  "id": 4,
  "text": "bombănind",
  "lemma": "bombăni",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 3,
  "deprel": "advcl",
  "start_char": 10406,
  "end_char": 10415
}
{
  "id": 14,
  "text": "bâlbâindu",
  "lemma": "bâlbâi",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 10499,
  "end_char": 10508
}
{
  "id": 38,
  "text": "căţărându",
  "lemma": "căţărî",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 31,
  "deprel": "advcl",
  "start_char": 10713,
  "end_char": 10722
}
{
  "id": 12,
  "text": "strigând",
  "lemma": "striga",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 41,
  "end_char": 49
}
{
  "id": 26,
  "text": "lovindu",
  "lemma": "lovi",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 21,
  "deprel": "advcl",
  "start_char": 10955,
  "end_char": 10962
}
{
  "id": 16,
  "text": "rătăcind",
  "lemma": "rătăci",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 13,
  "deprel": "advcl",
  "start_char": 11051,
  "end_char": 11059
}
{
  "id": 21,
  "text": "făcând",
  "lemma": "face",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 17,
  "deprel": "advcl",
  "start_char": 11236,
  "end_char": 11242
}
{
  "id": 17,
  "text": "întinzându",
  "lemma": "întinde",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 7,
  "deprel": "advcl",
  "start_char": 11365,
  "end_char": 11375
}
{
  "id": 13,
  "text": "străduindu",
  "lemma": "strădui",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 6,
  "deprel": "advcl",
  "start_char": 11492,
  "end_char": 11502
}
{
  "id": 9,
  "text": "luând",
  "lemma": "lua",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 17,
  "deprel": "advcl",
  "start_char": 11735,
  "end_char": 11740
}
{
  "id": 8,
  "text": "lătrând",
  "lemma": "lătra",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 4,
  "deprel": "advcl",
  "start_char": 11849,
  "end_char": 11856
}
{
  "id": 1,
  "text": "prefăcându",
  "lemma": "preface",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 12,
  "deprel": "advcl",
  "start_char": 11894,
  "end_char": 11904
}
{
  "id": 21,
  "text": "făcând",
  "lemma": "face",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 15,
  "deprel": "advcl",
  "start_char": 12188,
  "end_char": 12194
}
{
  "id": 15,
  "text": "aşteptându",
  "lemma": "aştepta",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 7,
  "deprel": "advcl",
  "start_char": 12334,
  "end_char": 12344
}
{
  "id": 1,
  "text": "crezând",
  "lemma": "crede",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 7,
  "deprel": "advcl",
  "start_char": 12473,
  "end_char": 12480
}
{
  "id": 12,
  "text": "făcând",
  "lemma": "face",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 7,
  "deprel": "advcl",
  "start_char": 12867,
  "end_char": 12873
}
{
  "id": 26,
  "text": "scoţând",
  "lemma": "scoate",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 23,
  "deprel": "conj",
  "start_char": 13272,
  "end_char": 13279
}
{
  "id": 5,
  "text": "gâfâind",
  "lemma": "gâfâi",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 19,
  "deprel": "advcl",
  "start_char": 13659,
  "end_char": 13666
}
{
  "id": 14,
  "text": "ţinându",
  "lemma": "ţina",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 5,
  "deprel": "conj",
  "start_char": 14042,
  "end_char": 14049
}
{
  "id": 15,
  "text": "sprijinindu",
  "lemma": "sprijini",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 12,
  "deprel": "advcl",
  "start_char": 14217,
  "end_char": 14228
}
{
  "id": 30,
  "text": "făcându",
  "lemma": "face",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 25,
  "deprel": "conj",
  "start_char": 14497,
  "end_char": 14504
}
{
  "id": 5,
  "text": "stăpânindu",
  "lemma": "stăpâni",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 1,
  "deprel": "advcl",
  "start_char": 14591,
  "end_char": 14601
}
{
  "id": 20,
  "text": "înălţându",
  "lemma": "înălţa",
  "upos": "VERB",
  "xpos": "Vmg-------y",
  "feats": "Variant=Short|VerbForm=Ger",
  "head": 14,
  "deprel": "advcl",
  "start_char": 14716,
  "end_char": 14725
}
{
  "id": 18,
  "text": "rostind",
  "lemma": "rosti",
  "upos": "VERB",
  "xpos": "Vmg",
  "feats": "VerbForm=Ger",
  "head": 10,

In [25]:
gerunziu_indices_and_lemmas

[(0, 'bombăni'),
 (1, 'vedea'),
 (2, 'aluneca'),
 (3, 'plimba'),
 (4, 'întreba'),
 (5, 'alerga'),
 (6, 'bombăni'),
 (7, 'încerca'),
 (8, 'întrebându'),
 (9, 'trage'),
 (10, 'găsi'),
 (11, 'face'),
 (12, 'întrebându'),
 (13, 'ţina'),
 (14, 'ţinca'),
 (15, 'bombăni'),
 (16, 'apropii'),
 (17, 'spune'),
 (18, 'încerca'),
 (19, 'izbucni'),
 (20, 'băga'),
 (21, 'spune'),
 (22, 'înota'),
 (23, 'sirădui'),
 (24, 'plescăi'),
 (25, 'aminti'),
 (26, 'clipi'),
 (27, 'tremura'),
 (28, 'temandu'),
 (29, 'continua'),
 (30, 'grăbi'),
 (31, 'stârni'),
 (32, 'tremura'),
 (33, 'şiroi'),
 (34, 'simţi'),
 (35, 'vorbi'),
 (36, 'spune'),
 (37, 'forma'),
 (38, 'lua'),
 (39, 'tremura'),
 (40, 'crunta'),
 (41, 'vorbi'),
 (42, 'întoarce'),
 (43, 'ridica'),
 (46, 'gâfâi'),
 (47, 'întreba'),
 (48, 'ţina'),
 (49, 'arăta'),
 (50, 'striga'),
 (51, 'întoarce'),
 (52, 'spune'),
 (53, 'lua'),
 (54, 'întoarce'),
 (55, 'ofta'),
 (56, 'măsura'),
 (57, 'uita'),
 (58, 'ridica'),
 (59, 'îndepărta'),
 (60, 'îndruge'),
 (61, 'suspine'),
 (62, 'zice'),
 (63, 'zice'),
 (64, 'crede'),
 (65, 'arunca'),
 (66, 'bombăni'),
 (67, 'alerga'),
 (68, 'temandu'),
 (69, 'pune'),
 (70, 'spune'),
 (71, 'spune'),
 (72, 'gândi'),
 (73, 'purta'),
 (74, 'uita'),
 (75, 'încerca'),
 (76, 'bombăni'),
 (77, 'bâlbâi'),
 (78, 'căţărî'),
 (79, 'striga'),
 (80, 'lovi'),
 (81, 'rătăci'),
 (82, 'face'),
 (83, 'întinde'),
 (84, 'strădui'),
 (85, 'lua'),
 (86, 'lătra'),
 (87, 'preface'),
 (88, 'face'),
 (89, 'aştepta'),
 (90, 'crede'),
 (91, 'face'),
 (92, 'scoate'),
 (93, 'gâfâi'),
 (94, 'ţina'),
 (95, 'sprijini'),
 (96, 'face'),
 (97, 'stăpâni'),
 (98, 'înălţa'),
 (100, 'rosti'),
 (101, 'încerca'),
 (102, 'ronţăi'),
 (103, 'coborî'),
 (104, 'realiza'),
 (105, 'dori'),
 (106, 'bate'),
 (107, 'văieta'),
 (108, 'nelua'),
 (109, 'începe'),
 (110, 'striga'),
 (111, 'aminti'),
 (112, 'aşeza'),
 (113, 'spune'),
 (114, 'întrebându'),
 (115, 'alerga'),
 (116, 'judeca'),
 (117, 'spune'),
 (118, 'schimba'),
 (119, 'vedea'),
 (120, 'sta'),
 (121, 'neţina'),
 (122, 'putea'),
 (123, 'începe'),
 (124, 'ţinca'),
 (125, 'rânji'),
 (126, 'sări'),
 (127, 'tremura'),
 (128, 'cânta'),
 (129, 'scutura'),
 (130, 'zvârli'),
 (131, 'întrebându'),
 (132, 'aduce'),
 (133, 'privi'),
 (134, 'alerga'),
 (135, 'întrebându'),
 (136, 'zări'),
 (137, 'neştia'),
 (138, 'continua'),
 (139, 'arăta'),
 (140, 'flutura'),
 (141, 'pieri'),
 (142, 'aştepta'),
 (143, 'dispărea'),
 (144, 'începe'),
 (145, 'sfârşi'),
 (146, 'spune'),
 (147, 'sprijini'),
 (148, 'vorbi'),
 (149, 'apropii'),
 (150, 'mulţumi'),
 (151, 'întoarce'),
 (152, 'scutura'),
 (153, 'duce'),
 (154, 'săgeta'),
 (155, 'negăsi'),
 (156, 'versa'),
 (157, 'întoarce'),
 (158, 'clătina'),
 (159, 'căsca'),
 (160, 'adresa'),
 (161, 'uita'),
 (162, 'zice'),
 (163, 'vrândni'),
 (164, 'căsca'),
 (165, 'şterge'),
 (166, 'scoate'),
 (167, 'vorbi'),
 (168, 'nădăjdui'),
 (169, 'vorbi'),
 (170, 'spune'),
 (171, 'spune'),
 (172, 'purta'),
 (173, 'ţina'),
 (174, 'purta'),
 (175, 'da'),
 (176, 'arăta'),
 (177, 'avea'),
 (178, 'nante'),
 (179, 'îndrepta'),
 (180, 'pune'),
 (181, 'rămâne'),
 (182, 'nădăjdui'),
 (185, 'uita'),
 (186, 'împiedica'),
 (187, 'atârna'),
 (188, 'peaştepta'),
 (190, 'vedea'),
 (191, 'urla'),
 (192, 'vorbi'),
 (193, 'veni'),
 (194, 'zâmbi'),
 (195, 'apropii'),
 (196, 'uita'),
 (197, 'ascunza'),
 (198, 'striga'),
 (199, 'condamna'),
 (200, 'bate'),
 (201, 'lua'),
 (202, 'porni'),
 (203, 'vorbi'),
 (204, 'lovi'),
 (205, 'lovi'),
 (206, 'sta'),
 (207, 'bate'),
 (208, 'profita'),
 (209, 'face'),
 (210, 'răcni'),
 (211, 'trage'),
 (212, 'vorbi'),
 (213, 'răsufla'),
 (214, 'şti'),
 (215, 'lăsa'),
 (216, 'lua'),
 (217, 'suspine'),
 (218, 'ofta'),
 (219, 'vrândni'),
 (220, 'privind'),
 (221, 'număra'),
 (222, 'ofta'),
 (223, 'ofta'),
 (224, 'încerca'),
 (225, 'începe'),
 (226, 'şiroi'),
 (227, 'spune'),
 (228, 'sări'),
 (229, 'înota'),
 (230, 'face'),
 (231, 'coborî'),
 (232, 'uita'),
 (233, 'călca'),
 (234, 'bate'),
 (235, 'trebui'),
 (236, 'arăta'),
 (237, 'începe'),
 (238, 'întrebându'),
 (239, 'grăbi'),
 (240, 'trage'),
 (241, 'gâfâi'),
 (242, 'păzi'),
 (243, 'uita'),
 (244, 'vedea'),
 (245, 'fale'),
 (246, 'întoarce'),
 (247, 'lăsa'),
 (248, 'uita'),
 (249, 'scula'),
 (250, 'auzi'),
 (251, 'guiţa'),
 (252, 'părea'),
 (253, 'căuta'),
 (254, 'aminti'),
 (255, 'întoarce'),
 (256, 'încrunta'),
 (257, 'schimonosi'),
 (258, 'freca'),
 (259, 'pune'),
 (260, 'uita'),
 (261, 'adresa'),
 (262, 'arăta'),
 (263, 'arunca'),
 (264, 'folosi'),
 (265, 'arunca'),
 (266, 'învineţi'),
 (267, 'da'),
 (268, 'alerga'),
 (269, 'gândi'),
 (270, 'cuprinde'),
 (271, 'face'),
 (272, 'stârni'),
 (273, 'porunci'),
 (274, 'amesteca'),
 (275, 'păstra'),
 (276, 'aduna'),
 (277, 'întrista'),
 (278, 'înveseli'),
 (279, 'veni'),
 (280, 'strădui'),
 (281, 'pâlpâi'),
 (282, 'studia'),
 (283, 'arăta'),
 (284, 'arde'),
 (285, 'lua'),
 (286, 'închide'),
 (287, 'gândi'),
 (288, 'şti'),
 (289, 'târşi'),
 (290, 'pipăi'),
 (291, 'acoperi'),
 (292, 'fierbe'),
 (293, 'duce'),
 (294, 'da'),
 (295, 'căuta'),
 (296, 'traversa'),
 (297, 'lua'),
 (298, 'despărţi'),
 (299, 'spărge'),
 (300, 'lăsa'),
 (301, 'alcătui'),
 (302, 'bloca'),
 (303, 'ţina'),
 (304, 'gândi'),
 (305, 'izbi'),
 (306, 'avea'),
 (307, 'avea'),
 (308, 'şterge'),
 (309, 'întinde'),
 (310, 'ţinca'),
 (311, 'pluti'),
 (312, 'căuta'),
 (313, 'întoarce'),
 (314, 'spera'),
 (315, 'călca'),
 (316, 'târşâi'),
 (317, 'coborî'),
 (318, 'urca'),
 (319, 'apuca'),
 (320, 'trage'),
 (321, 'strecura'),
 (322, 'trage'),
 (323, 'uita'),
 (324, 'atinge'),
 (325, 'rândui'),
 (326, 'încerca'),
 (327, 'ţinca'),
 (328, 'studia'),
 (329, 'bate'),
 (330, 'ţine'),
 (331, 'turna'),
 (332, 'uita'),
 (333, 'aproba'),
 (334, 'străluci'),
 (335, 'aştepta'),
 (336, 'lua'),
 (337, 'gândi'),
 (338, 'împărţi'),
 (339, 'sări'),
 (340, 'apuca'),
 (341, 'apuca'),
 (342, 'ţina'),
 (343, 'încerca'),
 (344, 'face'),
 (345, 'privi'),
 (346, 'uita'),
 (347, 'însufleţi'),
 (348, 'toca'),
 (349, 'mustra'),
 (350, 'ciupi'),
 (351, 'roti'),
 (352, 'spune'),
 (353, 'ţinca'),
 (354, 'chicoti'),
 (355, 'uita'),
 (356, 'atinge'),
 (357, 'studia'),
 (358, 'trage'),
 (359, 'ciufuli'),
 (360, 'spune'),
 (361, 'încerca'),
 (362, 'închide'),
 (363, 'tremura'),
 (364, 'şti'),
 (365, 'sclipi'),
 (366, 'închide'),
 (367, 'face'),
 (368, 'aştepta'),
 (369, 'păstra'),
 (370, 'chibzui'),
 (371, 'simti'),
 (372, 'zâmbi'),
 (373, 'măsura'),
 (374, 'ascunza'),
 (375, 'spune'),
 (376, 'mulţumi'),
 (377, 'freca'),
 (378, 'legăna'),
 (379, 'muta'),
 (380, 'încerca'),
 (381, 'veni'),
 (382, 'spune'),
 (383, 'lucra'),
 (384, 'asculta'),
 (385, 'pluti'),
 (386, 'rezema'),
 (387, 'pleca'),
 (388, 'spune'),
 (389, 'transforma'),
 (390, 'atârna'),
 (391, 'împinge'),
 (392, 'încerca'),
 (393, 'lăsa'),
 (394, 'clătina'),
 (395, 'lipi'),
 (396, 'pomeni'),
 (397, 'ţopăi'),
 (398, 'scutura'),
 (399, 'clătina'),
 (400, 'atârna'),
 (401, 'legăna'),
 (402, 'ţina'),
 (403, 'veni'),
 (404, 'mulţumi'),
 (405, 'evada'),
 (406, 'da'),
 (407, 'discuta'),
 (408, 'înghesui'),
 (409, 'ţinca'),
 (410, 'spune'),
 (411, 'apleca'),
 (412, 'încrunta'),
 (413, 'pleca'),
 (414, 'ţina'),
 (415, 'zâmbi'),
 (416, 'crede'),
 (417, 'lăsa'),
 (418, 'foi'),
 (419, 'folosi'),
 (420, 'indica'),
 (421, 'sta'),
 (422, 'urca'),
 (423, 'îndepărta'),
 (424, 'părăsi'),
 (425, 'râde'),
 (426, 'împături'),
 (427, 'urca'),
 (428, 'încui'),
 (429, 'minţi'),
 (430, 'întrebându'),
 (431, 'regreta'),
 (432, 'jura'),
 (433, 'duce'),
 (434, 'şti'),
 (435, 'întoarce'),
 (436, 'face'),
 (437, 'torca'),
 (438, 'hrăni'),
 (439, 'descrie'),
 (440, 'ţina'),
 (441, 'scoate'),
 (442, 'muta'),
 (443, 'bufni'),
 (444, 'căuta'),
 (445, 'chicoti'),
 (446, 'îndrepta'),
 (447, 'coborî'),
 (448, 'cânta'),
 (449, 'spune'),
 (450, 'apleca'),
 (451, 'zăbovi'),
 (452, 'spera'),
 (453, 'zâmbi'),
 (454, 'şterge'),
 (455, 'gândi'),
 (456, 'discuta'),
 (457, 'fugi'),
 (458, 'urmări'),
 (459, 'sprijini'),
 (460, 'încerca'),
 (461, 'trata'),
 (462, 'versa'),
 (463, 'ascunza'),
 (464, 'pune'),
 (465, 'îndepărta'),
 (466, 'vedea'),
 (467, 'zâmbi'),
 (468, 'cântări'),
 (469, 'turna'),
 (470, 'bate'),
 (471, 'amesteca'),
 (472, 'verifica'),
 (473, 'plânge'),
 (474, 'mirosi'),
 (475, 'duce'),
 (477, 'face'),
 (478, 'povesti'),
 (479, 'obliga'),
 (480, 'ţindu'),
 (481, 'convinge'),
 (482, 'lăsa'),
 (483, 'temandu'),
 (484, 'încrucişa'),
 (485, 'înălţa'),
 (486, 'ţinca'),
 (487, 'ţinca'),
 (488, 'ţinca'),
 (489, 'uita'),
 (490, 'ţinca'),
 (491, 'râde'),
 (492, 'temandu'),
 (493, 'şti'),
 (494, 'sprijini'),
 (495, 'prinde'),
 (496, 'ofta'),
 (497, 'pozenda'),
 (498, 'striga'),
 (499, 'râde'),
 (500, 'oblinge'),
 (501, 'sclipi'),
 (502, 'face'),
 (503, 'scrie'),
 (504, 'ridica'),
 (506, 'şezenda'),
 (507, 'mişca'),
 (508, 'strânge'),
 (509, 'simţi'),
 (510, 'folosi'),
 (511, 'purta'),
 (512, 'duce'),
 (513, 'călători'),
 (514, 'spune'),
 (515, 'ofta'),
 (516, 'promiţa'),
 (517, 'aburi'),
 (518, 'încerca'),
 (519, 'spera'),
 (520, 'zâmbi'),
 (521, 'trece'),
 (522, 'tremura'),
 (523, 'sprijini'),
 (524, 'fi'),
 (525, 'clăti'),
 (526, 'fierbe'),
 (527, 'spune'),
 (528, 'şterge'),
 (529, 'poticni'),
 (530, 'strânge'),
 (531, 'capta'),
 (532, 'veni'),
 (533, 'lușeca'),
 (534, 'lua'),
 (535, 'întinde'),
 (536, 'lăsa'),
 (537, 'spune'),
 (538, 'lăsa'),
 (539, 'ţipa'),
 (540, 'plimba'),
 (541, 'arăta'),
 (542, 'încrunta'),
 (543, 'aştepta'),
 (544, 'lua'),
 (545, 'întrebându'),
 (546, 'trece'),
 (547, 'da'),
 (548, 'vorbi'),
 (549, 'tremura'),
 (550, 'clătina'),
 (551, 'măcina'),
 (552, 'sta'),
 (553, 'privi'),
 (554, 'aştepta'),
 (555, 'atinge'),
 (556, 'strânge'),
 (557, 'atinge'),
 (558, 'numi'),
 (559, 'invoca'),
 (560, 'trebălui'),
 (561, 'vedea'),
 (562, 'urmări'),
 (563, 'redeveni'),
 (564, 'semeţi'),
 (565, 'îndreptî'),
 (566, 'opri'),
 (567, 'căuta'),
 (568, 'cuprinde'),
 (569, 'ridica'),
 (570, 'jucînd'),
 (571, 'juca'),
 (572, 'apue'),
 (574, 'umfla'),
 (575, 'face'),
 (576, 'răsuci'),
 (577, 'aruncî'),
 (578, 'însufleţi'),
 (579, 'ascultînd'),
 (581, 'privi'),
 (583, 'scude'),
 (584, 'destăinui'),
 (585, 'întoarce'),
 (586, 'lăsa'),
 (587, 'aruneînd'),
 (588, 'căsca'),
 (589, 'intrînd'),
 (590, 'refuza'),
 (591, 'întrebî'),
 (592, 'trage'),
 (593, 'tree'),
 (594, 'încrunta'),
 (595, 'aşeza'),
 (596, 'vorbi'),
 (597, 'vorbi'),
 (598, 'flecări'),
 (599, 'păstrî'),
 (600, 'încere'),
 (601, 'aştepta'),
 (602, 'agitî'),
 (603, 'sune'),
 (604, 'întârzia'),
 (605, 'strădui'),
 (606, 'face'),
 (607, 'şopti'),
 (608, 'ezitînd'),
 (609, 'îndreptî'),
 (610, 'face'),
 (611, 'păstra'),
 (612, 'căuta'),
 (613, 'comunica'),
 (614, 'înceta'),
 (615, 'opri'),
 (616, 'impune'),
 (617, 'arunca'),
 (618, 'constatînd'),
 (619, 'ilustrînd'),
 (620, 'opri'),
 (621, 'deschide'),
 (622, 'iradia'),
 (623, 'frcmătînd'),
 (624, 'întoarce'),
 (625, 'închipui'),
 (626, 'spulberi'),
 (627, 'lăsa'),
 (628, 'apue'),
 (629, 'fi'),
 (630, 'arătînd'),
 (631, 'şterge'),
 (632, 'băti'),
 (633, 'trece'),
 (634, 'privi'),
 (635, 'îndreptî'),
 (636, 'pierza'),
 (637, 'privi'),
 (638, 'cărînd'),
 (639, 'schimba'),
 (640, 'alunecînd'),
 (641, 'tresări'),
 (642, 'înşface'),
 (643, 'zbătî'),
 (644, 'dînd'),
 (645, 'tăia'),
 (646, 'arunca'),
 (647, 'plimba'),
 (648, 'reprezenta'),
 (649, 'urî'),
 (650, 'ridica'),
 (651, 'rizînd'),
 (652, 'izbucni'),
 (653, 'izbucni'),
 (654, 'surprinde'),
 (655, 'clătina'),
 (657, 'întrebî'),
 (658, 'trage'),
 (659, 'privind'),
 (660, 'aştepta'),
 (661, 'plonja'),
 (662, 'face'),
 (663, 'trage'),
 (664, 'duce'),
 (665, 'arătînd'),
 (666, 'discutînd'),
 (667, 'opri'),
 (668, 'privind'),
 (669, 'înainta'),
 (671, 'ascultînd'),
 (672, 'cutremura'),
 (673, 'arune'),
 (674, 'asuma'),
 (675, 'menţina'),
 (676, 'explica'),
 (677, 'părea'),
 (678, 'considerînd'),
 (679, 'murmura'),
 (680, 'ţine'),
 (681, 'dansî'),
 (682, 'substitui'),
 (683, 'tremura'),
 (684, 'iradia'),
 (685, 'desprinde'),
 (686, 'alegî'),
 (688, 'schimba'),
 (689, 'privind'),
 (690, 'şti'),
 (691, 'face'),
 (693, 'zbătî'),
 (694, 'dînde'),
 (695, 'adresa'),
 (696, 'bloca'),
 (697, 'adăuga'),
 (698, 'spălî'),
 (699, 'extragî'),
 (700, 'pipăi'),
 (701, 'clătina'),
 (702, 'respira'),
 (703, 'îndreptî'),
 (704, 'face'),
 (705, 'înconjurînd'),
 (706, 'reciti'),
 (707, 'aluneca'),
 (708, 'tremurînd'),
 (709, 'aştepta'),
 (710, 'umble'),
 (711, 'risipi'),
 (712, 'îndreptî'),
 (713, 'apleeîa'),
 (714, 'module'),
 (715, 'izbucni'),
 (716, 'descrie'),
 (718, 'sclipi'),
 (719, 'învîrti'),
 (720, 'avea'),
 (721, 'rătăci'),
 (722, 'arune'),
 (723, 'presupunînd'),
 (724, 'izbucni'),
 (725, 'manifesta'),
 (726, 'tresări'),
 (727, 'privi'),
 (729, 'întrebî'),
 (730, 'încerca'),
 (731, 'dînd'),
 (732, 'înfăţişa'),
 (733, 'arătînd'),
 (734, 'întinde'),
 (735, 'deschide'),
 (736, 'pune'),
 (737, 'munci'),
 (738, 'iradia'),
 (739, 'duce'),
 (740, 'face'),
 (741, 'încere'),
 (742, 'srînde'),
 (743, 'ţîfşnia'),
 (744, 'strînge'),
 (745, 'aminti'),
 (746, 'dînd'),
 (747, 'întoare'),
 (748, 'apleca'),
 (749, 'lăsa'),
 (750, 'urmari'),
 (751, 'pregăti'),
 (752, 'lăca'),
 (753, 'intrînd'),
 (754, 'ţine'),
 (755, 'mîngîia'),
 (756, 'uiti'),
 (757, 'naste'),
 (758, 'întreba'),
 (759, 'apropii'),
 (760, 'dînde'),
 (761, 'ascunza'),
 (762, 'dezvălui'),
 (763, 'veni'),
 (764, 'privi'),
 (765, 'sperî'),
 (766, 'invita'),
 (767, 'trage'),
 (768, 'judecînd'),
 (770, 'tresări'),
 (771, 'picurînd'),
 (772, 'crescînd'),
 (773, 'coborî'),
 (774, 'privi'),
 (775, 'tini'),
 (776, 'deschide'),
 (777, 'aduce'),
 (778, 'apăra'),
 (779, 'apleca'),
 (780, 'ridica'),
 (781, 'opri'),
 (782, 'privi'),
 (783, 'răspîndi'),
 (784, 'arăta'),
 (785, 'agitî'),
 (786, 'ţine'),
 (787, 'izbucni'),
 (788, 'trece'),
 (789, 'trece'),
 (790, 'intrînd'),
 (791, 'rătăci'),
 (792, 'rîzînd'),
 (793, 'reveni'),
 (794, 'închipui'),
 (795, 'examina'),
 (796, 'reprezenta'),
 (797, 'examini'),
 (798, 'şti'),
 (799, 'strigînd'),
 (800, 'întrerupe'),
 (801, 'depăşi'),
 (802, 'depăşi'),
 (803, 'adăuga'),
 (804, 'împodobi'),
 (805, 'lăsa'),
 (806, 'deveni'),
 (807, 'arunca'),
 (808, 'constitui'),
 (809, 'vrea'),
 (810, 'dispreţui'),
 (811, 'bănui'),
 (812, 'ridie'),
 (813, 'şti'),
 (815, 'dînde'),
 (816, 'tînde'),
 (817, 'ieşi'),
 (818, 'căuta'),
 (819, 'sunînd'),
 (820, 'face'),
 (822, 'dispărea'),
 (823, 'vorbi'),
 (824, 'semănînd'),
 (825, 'adăugi'),
 (826, 'dansînd'),
 (828, 'deschide'),
 (829, 'zbierînd'),
 (830, 'priyi'),
 (831, 'apleeîa'),
 (832, 'săruta'),
 (833, 'întoarce'),
 (834, 'însoţi'),
 (835, 'insufla'),
 (836, 'curme'),
 (837, 'opri'),
 (838, 'părea'),
 (839, 'dînd'),
 (840, 'închipui'),
 (841, 'ascultî'),
 (842, 'întrebî'),
 (843, 'pocni'),
 (844, 'înlocui'),
 (845, 'ţine'),
 (846, 'aduce'),
 (848, 'reţini'),
 (849, 'privind'),
 (850, 'săruti'),
 (851, 'privind'),
 (852, 'ţinînd'),
 (853, 'întinde'),
 (854, 'cuibări'),
 (855, 'strîngînd'),
 (856, 'întoarce'),
 (857, 'întinde'),
 (858, 'preceda'),
 (859, 'dînde'),
 (860, 'lupia'),
 (861, 'izbi'),
 (862, 'incerctna'),
 (863, 'privi'),
 (864, 'izbi'),
 (865, 'înfăşurînd'),
 (866, 'încrunta'),
 (867, 'descrie'),
 (868, 'împinge'),
 (869, 'atingî'),
 (870, 'lăsa'),
 (872, 'înţelege'),
 (873, 'stîrni'),
 (874, 'gîfîi'),
 (875, 'munci'),
 (876, 'sprijini'),
 (877, 'apăra'),
 (878, 'lăsa'),
 (879, 'lăsa'),
 (880, 'întoreînd'),
 (881, 'dispărea'),
 (882, 'adresa'),
 (883, 'potrivi'),
 (884, 'plîngî'),
 (885, 'întoarce'),
 (886, 'ascultînd'),
 (887, 'întoarce'),
 (888, 'îndreptmi'),
 (889, 'tremurînd'),
 (890, 'clăti'),
 (891, 'face'),
 (892, 'trece'),
 (893, 'arde'),
 (894, 'nege'),
 (895, 'apăra'),
 (896, 'încerca'),
 (897, 'zbătîa'),
 (898, 'chinumda'),
 (899, 'îndreptî'),
 (900, 'rîzenda'),
 (901, 'tremura'),
 (902, 'spunînd'),
 (903, 'îndreptî'),
 (905, 'ţipînd'),
 (906, 'amesti'),
 (907, 'trage'),
 (908, 'ţine'),
 (909, 'înăbuşi'),
 (910, 'scrie'),
 (911, 'corecta'),
 (912, 'legăni'),
 (913, 'ţine'),
 (914, 'opri'),
 (916, 'veni'),
 (917, 'continua'),
 (918, 'Âpuce'),
 (919, 'simţi'),
 (920, 'străbătînd'),
 (921, 'trece'),
 (922, 'gîfîi'),
 (923, 'privi'),
 (924, 'curge'),
 (925, 'pluti'),
 (926, 'încrunta'),
 (927, 'străluci'),
 (928, 'comanda'),
 (930, 'răsări'),
 (931, 'merge'),
 (933, 'apleca'),
 (934, 'acoperi'),
 (935, 'aprobî'),
 (936, 'apropii'),
 (937, 'lăsa'),
 (938, 'veghi'),
 (939, 'opri'),
 (940, 'începe'),
 (941, 'sprijini'),
 (942, 'căuta'),
 (943, 'căuta'),
 (944, 'fumi'),
 (945, 'vibrî'),
 (946, 'ofili'),
 (947, 'însufleţi'),
 (948, 'folosi'),
 (949, 'părăsi'),
 (950, 'nemailăsî'),
 (951, 'simţi'),
 (952, 'sta'),
 (953, 'povesti'),
 (954, 'strînge'),
 (955, 'distila'),
 (956, 'deschide'),
 (957, 'lăsa'),
 (958, 'privi'),
 (959, 'plimba'),
 (960, 'reveda'),
 (961, 'simţi'),
 (962, 'aşeza'),
 (963, 'aştepta'),
 (964, 'ocroti'),
 (965, 'simţi'),
 (966, 'hotărî'),
 (968, 'căuta'),
 (969, 'povesti'),
 (970, 'luî'),
 (971, 'povesti'),
 (972, 'suspine'),
 (973, 'încere'),
 (974, 'arătînd'),
 (976, 'frămînta'),
 (977, 'îndreptî'),
 (978, 'lipi'),
 (979, 'clălina'),
 (980, 'fixa'),
 (981, 'opri'),
 (982, 'luî'),
 (983, 'interesi'),
 (984, 'rămîne'),
 (985, 'exprima'),
 (986, 'răsări'),
 (987, 'gifîi'),
 (988, 'pierza'),
 (989, 'închipui'),
 (990, 'intrînd'),
 (991, 'ieşi'),
 (992, 'vorbi'),
 (993, 'gîndi'),
 (994, 'protesta'),
 (995, 'urî'),
 (996, 'înfăţişî'),
 (997, 'lăcrămînd'),
 (998, 'privind'),
 (999, 'înregistra'),
 (1000, 'încerca'),
 (1001, 'încerca'),
 (1002, 'curînd'),
 (1003, 'întinde'),
 (1004, 'remare'),
 (1005, 'zicînd'),
 (1006, 'plimba'),
 (1007, 'pîndi'),
 (1008, 'copia'),
 (1009, 'aştepta'),
 (1010, 'opri'),
 (1011, 'rriinuni'),
 (1012, 'murmurînd'),
 (1013, 'seîntei'),
 (1014, 'întoarce'),
 (1015, 'purtînd'),
 (1016, 'atîrnînd'),
 (1017, 'crezînd'),
 (1018, 'regreta'),
 (1019, 'mişe'),
 (1020, 'schimbi'),
 (1021, 'întinde'),
 (1022, 'răzbăti'),
 (1023, 'veni'),
 (1024, 'pleca'),
 (1025, 'lumina'),
 (1026, 'gîndi'),
 (1028, 'dînde'),
 (1029, 'repeta'),
 ...]

# Building combined df

In [26]:
gerunziu_indices_and_lemmas_df = pd.DataFrame(
    gerunziu_indices_and_lemmas, columns=["index", "lemma"]
).set_index("index")

In [27]:
adv_part_indices_and_words_df = pd.DataFrame(
    adv_part_indices_and_words, columns=["index", "adv_parts_and_lemmas"]
).set_index("index")

In [28]:
gerunziu_indices_and_lemmas_df

         lemma
index
0      bombăni
1        vedea
2      aluneca
3       plimba
4      întreba
...        ...
11257   întune
11258   folosi
11259     ieşi
11260    pluti
11261    sperî

[10881 rows x 1 columns]

In [29]:
adv_part_indices_and_words_df

        adv_parts_and_lemmas
index
5        [(hurrying, hurry)]
7      [(wondering, wonder)]
8      [(wondering, wonder)]
10         [(finding, find)]
14     [(muttering, mutter)]
...                      ...
11247       [(humming, hum)]
11248       [(humming, hum)]
11249       [(making, make)]
11253  [(splashing, splash)]
11259     [(leaving, leave)]

[5479 rows x 1 columns]

In [30]:
df = pd.concat(
    [df, gerunziu_indices_and_lemmas_df, adv_part_indices_and_words_df],
    axis=1,
)

In [31]:
df["is_gerunziu"] = False
df.loc[~df["lemma"].isna(), "is_gerunziu"] = True

In [32]:
df.head(2)

,1,2,3,4,5,6,7,8,romanian,lemma,adv_parts_and_lemmas,is_gerunziu
0,carroll-alenka_v_kraji,nu i se păru NEOBIŞNUIT nici chiar atunci când...,bombănind,:,carroll-alenka_v_kraji,,There was nothing so very remarkable in that; ...,,nu i se păru NEOBIŞNUIT nici chiar atunci când...,bombăni,NaN,True
1,carroll-alenka_v_kraji,,Văzând,"una ca asta , Alice se repezi în picioare ;",carroll-alenka_v_kraji,,but when the Rabbit actually took a watch out ...,,"Văzând una ca asta, Alice se repezi în picioare;",vedea,NaN,True

In [33]:
df["has_adv_participle"] = False
df.loc[~df["adv_parts_and_lemmas"].isna(), "has_adv_participle"] = True

In [34]:
len(df.loc[df["is_gerunziu"]])

10881

In [35]:
df.to_csv("extraction_output/annotated_all_ger_to_part.csv")

In [36]:
df.loc[df["is_gerunziu"] & df["has_adv_participle"]].to_csv(
    "extraction_output/gerunziu_with_adv_part.csv"
)

# Assigning gerunzius to adverbial participles

In [37]:
import functions_gensim

In [38]:
df = pd.read_csv("extraction_output/gerunziu_with_adv_part.csv", index_col=0)

In [39]:
for (
    i,
    row,
) in df.iterrows():
    gerunziu = row["3"]
    lemma_ro = row["lemma"]
    adv_parts_and_lemmas = eval(row["adv_parts_and_lemmas"])
    best_match = functions_gensim.get_best_match(
        word=gerunziu,
        lemma=lemma_ro,
        candidate_words_and_lemmas=adv_parts_and_lemmas,
        language_word="ro",
    )
    df.loc[i, ["best_match", "best_score"]] = best_match[0], best_match[1]

In [40]:
df.to_csv("extraction_output/ger_adv_matches.csv")